#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "202.112.113.22";
$SERVER_PORT = 18081;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
